name: apple_pay
description: A plugin to add Apple Pay support to your Flutter application.
version: 0.0.1
homepage: 

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: any # Add a version constraint (latest as of now)
  pay: any # Add a version constraint (adjust based on compatibility)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any # Add a version constraint

flutter:
  # If you use assets (e.g., local SVGs), declare them here
  # assets:
  #   - assets/icons/
